name: V40 Daily Sentry
on:
  schedule:
    - cron: '30 22 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 버전을 3.9로 낮춰서 호환성을 잡습니다
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas==2.0.3 pandas_ta requests
      - name: Run Sentry Engine
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python sentry.py
